#spring.application.name=ConstructionDrawingManagement
#
#custom.jwt.secret=9fpGEUpGqiplW2HJB7UDOpJScDgzJWJR5xqOP3zsJQKs8fuIQpvw37BP3hmNmb/9
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/online_forum"
    username: root
    password: root
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: drawing.system.team@gmail.com
    password: rfcilnorstiuynlo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  custom:
    jwt:
      secret: 9fpGEUpGqiplW2HJB7UDOpJScDgzJWJR5xqOP3zsJQKs8fuIQpvw37BP3hmNmb/9

#  profiles:
#    active: dev

#spring:
#  profiles:
#    active: @activatedProperties@