#spring.datasource.url=jdbc:mysql://localhost:3306/construction_drawing_management
#spring.datasource.username=sa
#spring.datasource.password=sa
#spring.jpa.hibernate.ddl-auto=update
#
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#server.error.include-stacktrace=never
#server.error.include-message=always
#
## Swagger_ui
#springdoc.api-docs.path=/info
#springdoc.swagger-ui.path=/
#springdoc.swagger-ui.operationsSorter=method

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/construction_drawing_management"
    username: root
    password: root
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: drawing.system.team@gmail.com
    password: rfcilnorstiuynlo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  error:
    include-stacktrace: never
    include-message: always
springdoc:
#  api-docs:
#    path: /info
#  swagger-ui:
#    path: /
#    operations-sorter: method
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html
    operations-sorter: method
logging:
  level:
    root: ERROR
    org.springframework: ERROR