#spring.application.name=ConstructionDrawingManagement
#
#custom.jwt.secret=9fpGEUpGqiplW2HJB7UDOpJScDgzJWJR5xqOP3zsJQKs8fuIQpvw37BP3hmNmb/9
spring:
  profiles:
    active: @activatedProperties@

  mail:
    host: smtp.gmail.com
    port: 587
    username: thangckdt@gmail.com
    password: bhwxmfnljndftdlv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com

  custom:
    jwt:
      secret: 9fpGEUpGqiplW2HJB7UDOpJScDgzJWJR5xqOP3zsJQKs8fuIQpvw37BP3hmNmb/9

#spring:
#  profiles:
#    active: @activatedProperties@