spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/online_forum"
    username: root
    password: root
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: update
    show-sql: true
  custom:
    jwt:
      secret: 9fpGEUpGqiplW2HJB7UDOpJScDgzJWJR5xqOP3zsJQKs8fuIQpvw37BP3hmNmb/9

#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: *insert email*
#    password: *insert key password*
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#
#  custom:
#    jwt:
#      secret: *insert secret key*
