spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/online_forum"
    username: root
    password: root
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: thangckdt@gmail.com
    password: bhwxmfnljndftdlv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  custom:
    jwt:
      secret: 9fpGEUpGqiplW2HJB7UDOpJScDgzJWJR5xqOP3zsJQKs8fuIQpvw37BP3hmNmb/9
  #setup cache for project
#  cache:
#    type: redis
#  redis:
#     host: redis-14089.c334.asia-southeast2-1.gce.redns.redis-cloud.com
#     port: 14089
#     password: gQt9d6tzgYPC9GI6RCdNGvvUdKGotWNO
#     username: default


#
#  custom:
#    jwt:
#      secret: *insert secret key*
